package org.ws4d.coap.proxy;

import java.net.InetAddress;

public class ProxyResourceKey {
	/* these variables are unique for one resource */
	private InetAddress inetAddr;
	private int port;
	private String path;
	
	public ProxyResourceKey(InetAddress inetAddr, int port, String path) {
		super();
		this.inetAddr = inetAddr;
		this.port = port;
		this.path = path;
	}
	
	/* hide default constructor */
	private ProxyResourceKey (){
		
	}
	
	//----------------GENERATED BY ECLIPSE---------------------------------
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((inetAddr == null) ? 0 : inetAddr.hashCode());
		result = prime * result + ((path == null) ? 0 : path.hashCode());
		result = prime * result + port;
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProxyResourceKey other = (ProxyResourceKey) obj;
		if (inetAddr == null) {
			if (other.inetAddr != null)
				return false;
		} else if (!inetAddr.equals(other.inetAddr))
			return false;
		if (path == null) {
			if (other.path != null)
				return false;
		} else if (!path.equals(other.path))
			return false;
		if (port != other.port)
			return false;
		return true;
	}
}
